Repository FRONTENDSCHOOL6/make-my-fridge-empty, pull requests merged in 2023-09, with the labels that each got.

#54 [add] SearchInput 컴포넌트 UI, 검색 기능 구현 완료
  src/assets/icons/svg-icons.js
  src/components/SearchInput.jsx
  src/pages/Search.jsx
  tailwind.config.js
Labels: 🧮 add, 🛠️ refactor, Tailwind, React

#55 [delete] searchResult 페이지 제거
  src/pages/SearchResult.jsx
  src/routes.jsx
Labels: ❎ delete

#59 [add] SearchInput 컴포넌트에 재료 검색 기능 추가
  src/components/SearchInput.jsx
  src/pages/AddIngredients.jsx
  src/pages/Search.jsx
  src/routes.jsx
Labels: 🧮 add, 🛠️ refactor, Tailwind, React

#77 [bug] Develop 브랜치 오류 수정
  src/components/button/Button.jsx
  src/components/button/Button.module.css
Labels: 🐞 bug, 📝 modify

#87 [modify] Search input 컴포넌트 조건부렌더링 코드 수정
  src/components/IngredientButtonSero.jsx
  src/components/SearchInput.jsx
  src/pages/Home.jsx
Labels: 🐞 bug

#94 [add] Ingredient button sero 구현 완료
  src/components/IngredientButtonSero.jsx
Labels: 🧮 add, 📝 modify, 🛠️ refactor

#113 [add] 재료를 담지 않은 회원이 접속했을 때 화면 전체가 보이지 않던 오류 해결
  src/components/IngredientButtonSero.jsx
  src/components/MenuItem.jsx
Labels: 🐞 bug, 🛠️ refactor, Tailwind, React

#114 [add] FridgeMenu페이지 완성, UI색깔 수정 완료, 다른 유저 정보 불러와지는 에러 수정, 냉장고 재료 추가 안되는 이슈 해결
  README.md
  src/components/BigMenuButton.jsx
  src/components/BigMenuList.jsx
  src/components/IngredientButtonGaro.jsx
  src/components/IngredientItemGaro.jsx
  src/pages/AddIngredients.jsx
  src/pages/FridgeMenu.jsx
  src/pages/Home.jsx
  src/pages/MyFridge.jsx
Labels: 🐞 bug, 📚 documentation, 🧮 add, Tailwind, React, PocketHost

#131 [modify] 다연님 피드백 위주로 전체 UI 2차 수정
  src/components/IngredientButtonSero.jsx
  src/pages/MyFridge.jsx
  src/pages/Search.jsx
Labels: 📝 modify, React
